# Глава 2

## 1. Подключение и работа с библиотекой numpy

1.1

In [4]:
import numpy as np

a = np.array([[2.3, 5.1, 4.7],
              [3.5, 6.7, 1.5],
              [8.4, 3.1, 9.2]])
b = np.array([[4.3, 8.1, 6.1],
              [3.7, 6.2, 1.5],
              [2.4, 5.7, 4.7]])

cols = len(a[0])    #столбцы
rows = len(a)       #строки
cols_2 = len(b[0])
rows_2 = len(b)

print('Массив а содержит ', cols, 'столбцов и ', rows, 'строк')
print('Массив b содержит ', cols_2, 'столбцов и ', rows_2, 'строк')

print('Сумма элементов массивов', a+b)
print('Разность элементов массивов' , a-b)
print('Произведение элементов массивов', a*b)
print('Разность элементов массивов' , a/b)

A = np.square(a)
B = b%2
print('Возведение в квадрат элементов массива а:', A)
print('Остаток от деления массива b на 2:', B)

S = np.cos(a)+np.sin(b)
print('Сумма косинусов массива a и синусов массива b', S)

Массив а содержит  3 столбцов и  3 строк
Массив b содержит  3 столбцов и  3 строк
Сумма элементов массивов [[ 6.6 13.2 10.8]
 [ 7.2 12.9  3. ]
 [10.8  8.8 13.9]]
Разность элементов массивов [[-2.  -3.  -1.4]
 [-0.2  0.5  0. ]
 [ 6.  -2.6  4.5]]
Произведение элементов массивов [[ 9.89 41.31 28.67]
 [12.95 41.54  2.25]
 [20.16 17.67 43.24]]
Разность элементов массивов [[0.53488372 0.62962963 0.7704918 ]
 [0.94594595 1.08064516 1.        ]
 [3.5        0.54385965 1.95744681]]
Возведение в квадрат элементов массива а: [[ 5.29 26.01 22.09]
 [12.25 44.89  2.25]
 [70.56  9.61 84.64]]
Остаток от деления массива b на 2: [[0.3 0.1 0.1]
 [1.7 0.2 1.5]
 [0.4 1.7 0.7]]
Сумма косинусов массива a и синусов массива b [[-1.58244196  1.34786755 -0.19455117]
 [-1.46629283  0.83129375  1.06823219]
 [ 0.15617453 -1.54982069 -1.97476688]]


1.2

In [5]:
import numpy as np

a = np.array([1.2, 2.4, 3.6, 3.5, 6.7, 1.5, 8.4, 3.1, 9.2])

#cols = len(a[0])
rows = len(a)

print('Количество строк', rows)

a.resize(9, 1)
print(a)


a.resize(3,3)
print(a)
mi = a.min(axis = 0)
mi_1 = a.min(axis = 1)
print('Минимальное число в столбце:', mi)
print('Минимальное число в строке:', mi_1)

ma = a.max(axis = 0)
ma_1 = a.max(axis = 1)
print('Максимальное число в столбце:', ma)
print('Максимальное число в строке:', ma_1)

s = a.sum(axis = 0)
s_1 = a.sum(axis = 1)
print('Сумма в столбцах:', s)
print('Сумма в строках:', s_1)

Количество строк 9
[[1.2]
 [2.4]
 [3.6]
 [3.5]
 [6.7]
 [1.5]
 [8.4]
 [3.1]
 [9.2]]
[[1.2 2.4 3.6]
 [3.5 6.7 1.5]
 [8.4 3.1 9.2]]
Минимальное число в столбце: [1.2 2.4 1.5]
Минимальное число в строке: [1.2 1.5 3.1]
Максимальное число в столбце: [8.4 6.7 9.2]
Максимальное число в строке: [3.6 6.7 9.2]
Сумма в столбцах: [13.1 12.2 14.3]
Сумма в строках: [ 7.2 11.7 20.7]


1.3

In [6]:
import numpy as np

a = np.array([[4,2], [9,1]])
b = np.array([[5,3], [2,5]])

M = np.row_stack([a,b])
print('Массив из 4-х строк и 2-х столбцов:')
print(M)

Sr = M[0:3, :]
print('Срез:')
print(Sr)

print('Сумма элементов:',Sr.sum())
print('Максимальный элемент:',Sr.max())
print('Минимальный элемент:',Sr.min())

N = np.column_stack([a,b])
print('Массив из 2-х строк и 4-х столбцов:')
print(N)

Sr_1 = N[:1, 0:3]
print('Срез:')
print(Sr_1)
print('Сумма элементов:',Sr_1.sum())
print('Максимальный элемент:',Sr_1.max())
print('Минимальный элемент:',Sr_1.min())

Массив из 4-х строк и 2-х столбцов:
[[4 2]
 [9 1]
 [5 3]
 [2 5]]
Срез:
[[4 2]
 [9 1]
 [5 3]]
Сумма элементов: 24
Максимальный элемент: 9
Минимальный элемент: 1
Массив из 2-х строк и 4-х столбцов:
[[4 2 5 3]
 [9 1 2 5]]
Срез:
[[4 2 5]]
Сумма элементов: 11
Максимальный элемент: 5
Минимальный элемент: 2


1.4

In [8]:
import numpy as np

M = np.array([[5, 4], [2, -6]])  #Матрица
V = np.array([14, -2])           #Вектор

O = np.linalg.solve(M,V)
print(O)

[2. 1.]


1.5

In [9]:
import numpy as np

A = np.array([[2,8], [1,-6]])
B = np.array([[3,2,7],[4,1,8],[6,3,7]])
C = np.array([[4,3,2,7], [6,1,1,-2], [7,5,8,1],[9,5,-3,-5]])

Tr_A = A.transpose()
Tr_B = B.transpose()
Tr_C = C.transpose()

print('Транспонированные матрицы:')
print(Tr_A)
print(Tr_B)
print(Tr_C)

Ob_A = np.linalg.inv(A)
Ob_B = np.linalg.inv(B)
Ob_C = np.linalg.inv(C)

print('Обратные матрицы:')
print(Ob_A)
print(Ob_B)
print(Ob_C)

Op_A = np.linalg.det(A)
Op_B = np.linalg.det(B)
Op_C = np.linalg.det(C)

print('Определитель матриц:')
print(Op_A)
print(Op_B)
print(Op_C)

N_B = np.linalg.norm(B,3,axis=1)

print('Норма векторов из строк матрицы 3x3:')
print(N_B)

N_C = np.linalg.norm(C,4,axis=0)

print('Норма векторов из столбцов матрицы 4x4:')
print(N_C)



Транспонированные матрицы:
[[ 2  1]
 [ 8 -6]]
[[3 4 6]
 [2 1 3]
 [7 8 7]]
[[ 4  6  7  9]
 [ 3  1  5  5]
 [ 2  1  8 -3]
 [ 7 -2  1 -5]]
Обратные матрицы:
[[ 0.3   0.4 ]
 [ 0.05 -0.1 ]]
[[-0.5483871   0.22580645  0.29032258]
 [ 0.64516129 -0.67741935  0.12903226]
 [ 0.19354839  0.09677419 -0.16129032]]
[[ 0.05464191  0.23129973 -0.05251989 -0.0265252 ]
 [-0.00424403 -0.37718833  0.11087533  0.16710875]
 [-0.06153846  0.03076923  0.10769231 -0.07692308]
 [ 0.13103448  0.02068966 -0.04827586 -0.03448276]]
Определитель матриц:
-20.000000000000007
31.0
1885.0000000000005
Норма векторов из строк матрицы 3x3:
[7.23042679 8.32514752 8.36820939]
Норма векторов из столбцов матрицы 4x4:
[10.1260949   6.04123954  8.04742813  7.42720632]


1.6

In [10]:
import numpy as np
import random

a = np.array([random.randint(0, 100) for i in range(0, 100, 1)])

print('Исходный массив:', a)
k = 0
for i in a:
    if i>50:
        k +=1
print('Количество элементов > 50: ', k)

print((a>50).sum())

Исходный массив: [ 30  99  82  58  37  86  97  79  88  19  12  46 100  10  51  24  58  17
  77  15   4  14  88 100  70  69  34  25  32  21  53  84  56  99  26   7
  20  55  59  30  98   1  47  84  71  77  87  74  83  28   6  79  40  17
  11  45  40  12  17   6  90  24  88  39  76   4  51  66  60  86  49  39
  38  87  61   2  19  96  68  17  61  92  85  41  27  28  36  35  32  25
  19  34  42  74  51  76  39  18  69   3]
Количество элементов > 50:  47
47
